In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("filtered_bulk_r.csv")

In [4]:
df = df.round(4)

In [5]:
df.head()

,fl_dur,tot_fw_pk,tot_bw_pk,fw_pkt_l_max,fw_pkt_l_min,fw_pkt_l_avg,fw_pkt_l_std,bw_pkt_l_max,bw_pkt_l_min,bw_pkt_l_mean,...,bw_iat_tot,bw_iat_avg,bw_iat_std,bw_iat_max,bw_iat_min,fw_pkt_s,bw_pkt_s,pkt_size_avg,Label_code,Label_Desc
0,0.0001,2,2,79,48,63.5,21.9203,61,48,54.5,...,0.0,0.0,0.0,0.0,0.0,21290.8832,17084.7413,59.0,1,Attack
1,0.0002,2,2,79,48,63.5,21.9203,61,48,54.5,...,0.0,0.0,0.0,0.0,0.0,12192.7442,12427.5674,59.0,1,Attack
2,0.0001,2,2,79,48,63.5,21.9203,61,48,54.5,...,0.0,0.0,0.0,0.0,0.0,25653.2355,26973.0161,59.0,1,Attack
3,0.0001,2,2,79,48,63.5,21.9203,61,48,54.5,...,0.0,0.0,0.0,0.0,0.0,19599.5514,19065.0182,59.0,1,Attack
4,0.0002,2,2,79,48,63.5,21.9203,61,48,54.5,...,0.0,0.0,0.0,0.0,0.0,16256.9922,14926.3488,59.0,1,Attack

In [6]:
df.to_csv("filtered_bulk_rounded.csv", index=False)